builders:
  tool_builder:
    import: "package:native_ai_bridge_generator/builder.dart"
    builder_factories: ["toolBuilder"]
    build_extensions: {".dart": [".tool.g.dart"]}
    auto_apply: dependents
    build_to: source
